service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: ap-southeast-2
  apiName: protolith-app

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: 'POST /batch_predict'
      - http: 'POST /single_predict'
    role: arn:aws:iam::754302797117:role/lambda-role
    memorySize: 2048
    timeout: 15